package io.codeswarm.schauberger.physics

import io.codeswarm.schauberger.math.Vector3D
import io.codeswarm.schauberger.model.Particle

/** Strategy calculating one acceleration contribution for a particle. */
trait FlowForce {
  /** Calculates acceleration generated by this force model. */
  def acceleration(particle: Particle, context: FlowContext): Vector3D
}
